//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSDBEntities1 : DbContext
    {
        public LMSDBEntities1()
            : base("name=LMSDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessionMapping> AssessionMapping { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookCategory> BookCategory { get; set; }
        public virtual DbSet<BookIssueReturn> BookIssueReturn { get; set; }
        public virtual DbSet<Fine> Fine { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberCategory> MemberCategory { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
    }
}
